[build]
  publish = "."
  command = "echo 'No build command needed for static site'"
  functions = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(self)"

[[redirects]]
  from = "/ngerug"
  to = "/log.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

